### ISSUE TITLE
500 Hz output and strange z accel values

### ISSUE THREAD

**Issue by mcamurri** [openhumanoids/microstrain#1]
I've just tried plugging in my GX3-25 and running this driver. 

From bot spy I see a constant frame rate of 500 Hz (even though the default or manually selected option is 100 Hz) and that the acceleration value oscillates around -1.96 m/s^2.

The ROS driver is outputting a value of -9.78 m/s^2 which is kind of OK. 

Have you ever experienced something similar? 

I'm using latest version and I tried both the version pointed by inside pronto-distro and a fresh, cloned version of this repo.

**Comment by mauricefallon** [comment]
(this is the IMU that is on Valkyrie currently)

The driver is about 400 lines of code in one file so it can't be doing much. I see a GRAVITY variable...
If you could have it support 500 Hz that would be really useful.

**Comment by mcamurri** [comment]
Indeed. Funny fact is that even if I wanted, I couldn't run it at less (or more) than 500 Hz. 

Can you confirm that the output with the same code on Valkyrie does produce this weird value for `accel[2]`?

I can't access another GX-3 now, and also I doubt it is the IMU itself because the ROS driver works. I'd rather prefer the LCM one because it computes the realignment in time, so in Signal Scope I don't see unevenly spaced messages.

**Comment by mauricefallon** [comment]
I can't. the robot hasn't arrived yet. sorry.

> I can't access another GX-3 now, and also I doubt it is the IMU itself because the ROS driver works. 
> I'd rather prefer the LCM one because it computes the realignment in time, so in Signal Scope I don't 
>  see unevenly spaced messages.

What you mean is that LCM's message passing can properly support 500Hz and ROS message passing cannot. which is problematic ;)

**Comment by mauricefallon** [comment]
But if you have a look at the code, basically its receiving a stream of messages from the serial port and they are being unpacked into ins_message.accel. Then they are scaled by GRAVITY 9.80665. 

Is this scaling different for your sensor (i.e. or are the messages just junk? The ratio 1.96:9.80 is very close to 500:100. I dont know why that would be the case but both ROS and LCM drivers are decoding this stream and quickly packing it into messages.

**Comment by mcamurri** [comment]
I don't think the gravity constant is the problem, from the datasheet it corresponds to what is hardcoded.  Instead, the ratio 5:1 seems a good intuition, thanks for pointing this out.
**EDIT**
The 5:1 ratio actually had something to do with the issue. I tried to run it with the `--rate m` option and it outputs the correct value. With the argument `--rate l` instead of running at 100 Hz, it runs at 500 Hz but outputs values at 1/5 of the true measure. Weird.

**Comment by mcamurri** [comment]
We'll keep the medium rate when launching the driver.
