### ISSUE TITLE
lcmtype definition migration to bot_core

### ISSUE THREAD

**Issue by mcamurri** [openhumanoids/microstrain#2]
this imu module is producing its own version of ins type, `microstrain::ins_t`, but most of pronto_distro modules are migrating to `bot_core` messages, and it defines a `bot_core::ins_t` itself.

As long as the two definitions are the same, a module which tries to decode a `microstrain::ins_t` into a `bot_core::inst_t` should succeed. 

But if in the future for any reason would they will differ, either we should account for the microstrain case only, or modify the driver to use bot_core::ins_t.

Should we keep microstrain::ins_t  to have this repo it self-contained, or migrate to `bot_core::ins_t`?

**Comment by mauricefallon** [comment]
I believe we should keep microstrain::ins_t because it doesn't create a dependency on bot_core message. (I guess you noticed by now that microstrain::ins_t appears exactly the same as bot_core::ins_t to any process subscribing to it)

`But if in the future for any reason would they will differ, either we should account for the microstrain case only, or modify the driver to use bot_core::ins_t.`

I agree, certainly.

**Comment by mcamurri** [comment]
Actually, this package already depends on `bot_core`
https://github.com/openhumanoids/microstrain/blob/master/src/microstrain_comm.cpp#L15
https://github.com/openhumanoids/microstrain/blob/master/src/microstrain_pose.cpp#L5
`bot_core.hpp` contains inside a reference to `bot_core::ins_t`

if you don't want a dependency on `bot_core`, then you should remove it.

**Comment by mauricefallon** [comment]
Good point. Bot core is certainly required for timesync. In this case I agree with your original suggestion - best to not duplicate if the code is actually dependent.

Is this a big issue for you? If so please make a PR, happy to accept.

**Comment by mcamurri** [comment]
I noticed some issues in the past when you migrated from `pronto::pointcloud_t` to `bot_core::pointcloud_t`, where the message slightly changed. 

Also I remember about another message type, maybe `microstrain` itself, that changed from `uint64_t` to `int64_t`for `utime`. 

In general, I have the feeling that the less duplicates there are, the less problems we can raise.

My merge request is ready, here:
https://github.com/openhumanoids/microstrain/pull/3

You'll need to rollup the submodule from `pronto-distro` as well.
